name: liveinfo
description: Wheather, News and Stocks app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^3.0.1
  http: ^0.12.0+2
  url_launcher: ^5.4.5
  loading: ^1.0.2
  dynamic_theme: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
